/**
 * Cloud 9 IAM API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface User { 
    id?: string;
    firstName?: string;
    lastName?: string;
    displayName?: string;
    displayImageURL?: string;
    email?: string;
    created?: string;
    updated?: string;
}

